import Foundation

struct Quote {
    let text: String
    let author: String?
}

enum Quotes {
    static let all: [Quote] = [
        Quote(text: "How we spend our days is, of course, how we spend our lives.",
              author: "Annie Dillard"),
        Quote(text: "The present moment is the only time over which we have dominion.",
              author: "Thích Nhất Hạnh"),
        Quote(text: "It is not that we have a short time to live, but that we waste a lot of it.",
              author: "Seneca"),
        Quote(text: "Rest is not idleness, and to lie sometimes on the grass under trees on a summer's day is by no means a waste of time.",
              author: "John Lubbock"),
        Quote(text: "Tell me, what is it you plan to do with your one wild and precious life?",
              author: "Mary Oliver"),
        Quote(text: "Nature does not hurry, yet everything is accomplished.",
              author: "Lao Tzu"),
        Quote(text: "You have power over your mind — not outside events. Realize this, and you will find strength.",
              author: "Marcus Aurelius"),
        Quote(text: "In an age of speed, nothing could be more invigorating than going slow.",
              author: "Pico Iyer"),
        Quote(text: "Almost everything will work again if you unplug it for a few minutes, including you.",
              author: "Anne Lamott"),
        Quote(text: "The quieter you become, the more you can hear.",
              author: "Ram Dass"),
        Quote(text: "Wherever you are, be there totally.",
              author: "Eckhart Tolle"),
        Quote(text: "Walk as if you are kissing the Earth with your feet.",
              author: "Thích Nhất Hạnh"),
        Quote(text: "The unexamined life is not worth living.",
              author: "Socrates"),
        Quote(text: "Happiness depends upon ourselves.",
              author: "Aristotle"),
        Quote(text: "The greatest wealth is to live content with little.",
              author: "Plato"),
        Quote(text: "No man ever steps in the same river twice, for it is not the same river and he is not the same man.",
              author: "Heraclitus"),
        Quote(text: "He who has a why to live can bear almost any how.",
              author: "Friedrich Nietzsche"),
        Quote(text: "Waste no more time arguing what a good person should be. Be one.",
              author: "Marcus Aurelius"),
        Quote(text: "Very little is needed to make a happy life; it is all within yourself, in your way of thinking.",
              author: "Marcus Aurelius"),
        Quote(text: "We suffer more often in imagination than in reality.",
              author: "Seneca"),
        Quote(text: "To be everywhere is to be nowhere.",
              author: "Seneca"),
        Quote(text: "The only true wisdom is in knowing you know nothing.",
              author: "Socrates"),
        Quote(text: "It is not enough to be busy. So are the ants. The question is: What are we busy about?",
              author: "Henry David Thoreau"),
        Quote(text: "Our life is frittered away by detail. Simplify, simplify.",
              author: "Henry David Thoreau"),
        Quote(text: "The price of anything is the amount of life you exchange for it.",
              author: "Henry David Thoreau"),
        Quote(text: "Adopt the pace of nature: her secret is patience.",
              author: "Ralph Waldo Emerson"),
        Quote(text: "Nothing can bring you peace but yourself.",
              author: "Ralph Waldo Emerson"),
        Quote(text: "All I have seen teaches me to trust the Creator for all I have not seen.",
              author: "Ralph Waldo Emerson"),
        Quote(text: "Do not spoil what you have by desiring what you have not.",
              author: "Epicurus"),
        Quote(text: "If you are distressed by anything external, the pain is not due to the thing itself, but to your estimate of it.",
              author: "Marcus Aurelius"),
        Quote(text: "No great thing is created suddenly.",
              author: "Epictetus"),
        Quote(text: "First say to yourself what you would be; and then do what you have to do.",
              author: "Epictetus"),
        Quote(text: "How much more grievous are the consequences of anger than the causes of it.",
              author: "Marcus Aurelius"),
        Quote(text: "All of humanity's problems stem from man's inability to sit quietly in a room alone.",
              author: "Blaise Pascal"),
        Quote(text: "Life can only be understood backwards; but it must be lived forwards.",
              author: "Soren Kierkegaard"),
        Quote(text: "Well-being is attained little by little, and nevertheless is no little thing itself.",
              author: "Zeno of Citium"),
        Quote(text: "Be patient toward all that is unsolved in your heart and try to love the questions themselves.",
              author: "Rainer Maria Rilke"),
        Quote(text: "No one saves us but ourselves. No one can and no one may. We ourselves must walk the path.",
              author: "Buddha"),
        Quote(text: "Every morning we are born again. What we do today is what matters most.",
              author: "Buddha"),
        Quote(text: "Peace comes from within. Do not seek it without.",
              author: "Buddha"),
        Quote(text: "When walking, walk. When eating, eat.",
              author: "Zen proverb"),
        Quote(text: "The obstacle is the path.",
              author: "Zen proverb"),
        Quote(text: "Do every act of your life as though it were the very last act of your life.",
              author: "Marcus Aurelius"),
        Quote(text: "If you seek tranquility, do less.",
              author: "Marcus Aurelius"),
        Quote(text: "You did what you came to do. That is enough.",
              author: nil),
        Quote(text: "Your eyes have carried you this far. Let them rest on something distant.",
              author: nil),
        Quote(text: "Stepping away is part of the work.",
              author: nil),
        Quote(text: "The screen will keep. Go stretch, breathe, look out a window.",
              author: nil),
        Quote(text: "Look up. The room is still here, and so are you.",
              author: nil),
        Quote(text: "Blink slowly. Your eyes have earned gentleness.",
              author: nil),
        Quote(text: "Leave one thing unfinished: your habit of hurrying.",
              author: nil),
        Quote(text: "Breathe out the urgency that no longer serves you.",
              author: nil),
        Quote(text: "You can return sharper by leaving softer.",
              author: nil),
        Quote(text: "Today did not require perfection. It required presence.",
              author: nil),
        Quote(text: "Stand up as if your future self asked you to.",
              author: nil),
    ]

    static func random() -> Quote {
        all.randomElement()!
    }
}
